-- MiniMinds Academy: production Supabase/PostgreSQL schema
--
-- Apply with a privileged database connection (for example `psql -f ...`).
-- The Flask service uses the server-side Postgres pooler connection; do not put
-- database passwords, service-role keys, or Cloudinary credentials in this file.

BEGIN;

CREATE TABLE IF NOT EXISTS parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL CHECK (char_length(password_hash) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS parents_email_unique ON parents (lower(email));

CREATE TABLE IF NOT EXISTS children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
    age SMALLINT NOT NULL CHECK (age BETWEEN 4 AND 9),
    pin_hash TEXT NOT NULL CHECK (char_length(pin_hash) > 0),
    points INTEGER NOT NULL DEFAULT 0 CHECK (points >= 0),
    xp INTEGER NOT NULL DEFAULT 0 CHECK (xp >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS children_parent_id_idx ON children (parent_id, id DESC);

CREATE TABLE IF NOT EXISTS completions (
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    lesson_key TEXT NOT NULL CHECK (char_length(lesson_key) BETWEEN 1 AND 200),
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (child_id, lesson_key)
);
CREATE INDEX IF NOT EXISTS completions_child_completed_idx ON completions (child_id, completed_at DESC);

-- Immutable award ledger gives support and finance-style auditability.  The
-- unique key prevents a retry from granting a lesson reward twice.
CREATE TABLE IF NOT EXISTS reward_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    completion_lesson_key TEXT NOT NULL,
    xp_delta INTEGER NOT NULL CHECK (xp_delta >= 0),
    points_delta INTEGER NOT NULL CHECK (points_delta >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (child_id, completion_lesson_key),
    FOREIGN KEY (child_id, completion_lesson_key)
        REFERENCES completions (child_id, lesson_key) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS reward_events_child_created_idx ON reward_events (child_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS parents_set_updated_at ON parents;
CREATE TRIGGER parents_set_updated_at BEFORE UPDATE ON parents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS children_set_updated_at ON children;
CREATE TRIGGER children_set_updated_at BEFORE UPDATE ON children
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
